import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Tagesschrift, Pacifico } from 'next/font/google'
import Navbar from "@/components/Navbar";
import { AuthProvider } from "@/contexts/AuthContext";
const tagesschrift = Tagesschrift({
  subsets: ['latin'],
  weight: '400', // adjust if needed
  variable: '--font-tagesschrift',
  display: 'swap',
})
const pacifico = Pacifico({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-pacifico',
  display: 'swap',
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Edens Home - Get Your Next Destination",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  ${pacifico.variable}`}
      >
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
